### PR TITLE
ENH: Add NGFF 0.4 JSON Schema validation test

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by thewtex** [comment]
Based on the work of @sbesson :pray:

**Comment by sbesson** [comment]
Thanks for the heads up @thewtex. With https://github.com/ome/ngff/pull/113 now merged, https://ngff.openmicroscopy.org/0.4/schemas/image.schema and other schemas should now start resolving and I assume the downstream packages can start consuming these.

As mentioned in https://github.com/ome/ngff/issues/58, there are a few scalability and usability downsides with dynamically retrieving remote schemas  for eac validation. I suspect there will be a use case for distributing these schemas as library resources  but we have not yet established the best language-agnostic way to structure this.

**Comment by sbesson** [comment]
Thanks for the heads up @thewtex. With https://github.com/ome/ngff/pull/113 now merged, https://ngff.openmicroscopy.org/0.4/schemas/image.schema and other schemas should now start resolving and I assume the downstream packages can start consuming these.

As mentioned in https://github.com/ome/ngff/issues/58, there are a few scalability and usability downsides with dynamically retrieving remote schemas  for eac validation. I suspect there will be a use case for distributing these schemas as library resources  but we have not yet established the best language-agnostic way to structure this.

**Comment by thewtex** [comment]
> Thanks for the heads up @thewtex. With ome/ngff#113 now merged, https://ngff.openmicroscopy.org/0.4/schemas/image.schema and other schemas should now start resolving and I assume the downstream packages can start consuming these.

@sbesson wonderful, thank you!

Migrating to this in #27 

> As mentioned in ome/ngff#58, there are a few scalability and usability downsides with dynamically retrieving remote schemas for eac validation. I suspect there will be a use case for distributing these schemas as library resources but we have not yet established the best language-agnostic way to structure this.

Yes, packages that could be used offilne would be nice.

**Pull request merged**
